const CounterActionTypes = {
  ADD_COURSE: "ADD_COURSE",
  ADD_COURSE_BEGIN: "ADD_COURSE_BEGIN",
  ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
  ADD_COURSE_ERROR: "ADD_COURSE_ERROR",
  LOAD_COURSES_BEGIN: "LOAD_COURSES_BEGIN",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
  LOAD_COURSES_ERROR: "LOAD_COURSES_ERROR",
  OPEN_NEW_COURSE_MODAL: "OPEN_NEW_COURSE_MODAL",
  CLOSE_NEW_COURSE_MODAL: "CLOSE_NEW_COURSE_MODAL"
};

export default CounterActionTypes;
